### ISSUE TITLE
Add powerslice and necessary precursors

### ISSUE THREAD

**Issue by dolio** [unisonweb/base2#2]
The changes summarized below are available for you to review, using the
  following command:

    `pr.load https://github.com/unisonweb/base2 https://github.com/dolio/base2`

  Added definitions:

    1. List.init       : [a] -> [a] (+2 metadata)
    2. List.inits      : [a] -> [[a]] (+2 metadata)
    3. List.powerslice : [a] -> [[a]] (+2 metadata)
    4. List.tails      : [a] -> [[a]] (+2 metadata)

**Comment by runarorama** [comment]
Looks good!
